# Generated by Django 4.1.7 on 2023-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
